### ISSUE TITLE
Removing moment library usage/dependency to make dependent libraries smaller

### ISSUE THREAD

**Issue by asergeev-sc** [OpusCapita/i18n#13]
Moment is a rather large library which size is much bigger that i18n code itself. Try to find the way of transforming Date to String and String to Date (using [java.text.SimpleDateFormat](https://docs.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html) date patterns) without Moment.

**Comment by kvolkovich-sc** [comment]
Done. Released in `@opuscapita/i18n@1.2.2`.
