### ISSUE TITLE
Introduce new integer/decimal converter for big numbers

### ISSUE THREAD

**Issue by ddivin-sc** [OpusCapita/i18n#32]
Meta-Info | Value
-- | --
ExtProjectId | JCPROC-01
Original Estimation | ???h
Remaining Estimation | ???h

Description
---

Current integer/decimal converter have a problem with big numbers. This problem in places technical limitation of JavaScript core. The MAX_SAFE_INTEGER constant has a value of 9007199254740991 (9,007,199,254,740,991 or ~9 quadrillion)

Source Value | Expected Value | Actual Value | Format
------------------ | -------------------- | ------------------ | ------------------
9007199254740989.07 |  9,007,199,254,740,989.07 | 9,007,199,254,740,990.00  | #,###.00
21321312312312344 |  21321312312312344.00 | error | #.00
99999999999999999.99 |  99999999999999999.99| 99999999999999999.00 | #.00

Solution
---
The idea is to create a converter that converts the value of a string, for example:

```
let c = new BigNumberConverter('#,##0.00', ',', '.');
c.valueToString('9007199254740989.07') === '9,007,199,254,740,989.07' //true
c.stringToValue('9,007,199,254,740,989.07') === '9007199254740989.07' //true
 ```

Adjustment API for I18nManager
```JavaScript
class I18nManager {
  ...
  <string> formatBigDecimalNumber(<string> numberAsString)
  <string> formatDecimalNumberWithPattern(<string> numberAsString, <string> numberPattern)
  <string> formatBigNumber(<string> numberAsString)
  <string> parseBigDecimalNumber(<string> value)
  <string> parseBigNumber(<string> value)
}
``` 

Original issue: https://github.com/OpusCapita/minsk-core-externals/issues/585

**Comment by ddivin-sc** [comment]
Please, review my changes.

**Comment by asergeev-sc** [comment]
See my comments in [PR](https://github.com/OpusCapita/i18n/pull/33#pullrequestreview-390499088)
