### ISSUE TITLE
Improve I18nManager.getMessage interaction with keys which contains point symbol

### ISSUE THREAD

**Issue by apyrkh-sc** [OpusCapita/i18n#4]
Currently when a translation key contains a point like `user.organization.name` _I18nManager.getMessage_ is splitting the code by point and trying to get a property as nested object, e.g.:
`{ user: { organization: { name: 'My organization name' } } }`
If the message is not found the is used as a message.
This is not user friendly and it's not conveniently to work with that.

The proposal is to improve _I18nManager.getMessage_ by adding a new step at the beginning, so the login would be:
1) find the message by the raw code, like `{ 'user.organization.name': 'My organization name' }`
2) if not found then find the message in nested object `{ user: { organization: { name: 'My organization name' } } }`
3) if not found return the key as a message `user.organization.name`

**Comment by asergeev-sc** [comment]
Ticket is resolved by this commit: https://github.com/OpusCapita/i18n/commit/e4c8c00a115c9f67a5795bed60b8f4a233fc8610
